server:
    port: 9080

spring:
    profiles:
        active: dev
    #开启aop功能
    aop:
        auto: true
    jmx:
        default-domain: "websc-mp"

projectDomainName: localhost

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.sc.mp.model
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  config: classpath:log4j2.xml
  level:
    com.sc.mp.mapper: debug

sc:
    role:
        super: 7
        regional: 4
        doctor: 5
    page:
        login: login
        super: super
        regional: regional
        doctor: doctor
    stats:
        top: 2
