server:
    port: 9080
spring:
    profiles:
        active: dev
    #开启aop功能
    aop:
        auto: true
    jmx:
        default-domain: "websc-mp"

projectDomainName: fw1.sucheng-group.com:9080
dirPath: /home/photo

mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: com.sc.mp.model
    configuration:
        mapUnderscoreToCamelCase: true

logging:
    config: classpath:log4j2.xml
    level:
        com.sc.mp.mapper: debug

sc:
    role:
        super: 7
        regional: 4
        doctor: 5
        nurse: 6
    page:
        login: login
        super: super
        regional: regional
        doctor: doctor
        nurse: nurse
    wx:
        #login: https://open.weixin.qq.com/connect/oauth2/authorize?appid=ww0a5757d175c0cfc6&redirect_uri=http%3a%2f%2ffw1.sucheng-group.com%3a9080%2findex&response_type=code&scope=snsapi_base&state=gologin#wechat_redirect
        login: /index?code=testCode&state=gologin
    stats:
        top: 5
