spring:
    datasource:
        name: mysql
        #url: jdbc:mysql://47.100.162.75:3310/SAJT_SC_NEW?characterEncoding=UTF-8
        url: jdbc:mysql://47.100.162.75:3310/MYSQL-SC?characterEncoding=UTF-8
        username: root
        password: Root@1234
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
    http: 
        multipart: 
            max-file-size: 100MB
            max-request-size: 200MB
redis:
    host: 106.14.164.162
    port: 36380
#企业微信配置项
wx:
    corpid: ww0a5757d175c0cfc6
    corpsecret: tnRFaSEmGEXg1mWMpox527dQFhBQgWE2JBLRhZ7xyew
# 微信小程序所需配置
operativeName-lucene-path: D:\\lucene\\lucene-db\\sc\\operativeName
wx-appid: wx5139fc8c8b8878f7
wx-secret: f46eab7526212299671b17e854a2a5d7
wx-api-uri: https://api.weixin.qq.com/sns/jscode2session?
lucene-token: operativeluceneupdtoken1234

userName-lucene-path: D:\\lucene\\lucene-db\\sc\\userName

wx-gzh-appid: wxfdc16ad1198bf14a
wx-gzh-secret: b3db511490703a3c474f55be87f104c7
wx-gzh-api-uri: https://api.weixin.qq.com/cgi-bin/
gzh-media-cron-expression: 0 5 14 * * ?
statistics-org-operative-cron-expression: 0 1 17 * * ?