server:
    port: 80

spring:
  profiles:
    active: dev

projectDomainName: localhost

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.sc.mp.model
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  config: classpath:log4j2.xml
  level:
    com.sc.mp.mapper: debug

sc:
    role:
        super: 7
        regional: 4
        doctor: 5
    page:
        login: login
        super: super
        regional: regional
        doctor: doctor
